apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-samplerestapi-service
spec:
  selector:
    app: {{ .Release.Name }}-samplerestapi
  ports:
    - name: rest
      protocol: TCP
      port: 4000
